/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RestaurantId = IDL.Text;
export const CreateMenuItemArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Restaurant = IDL.Record({
  'rid' : RestaurantId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Ready' : IDL.Null,
  'Preparing' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customer' : IDL.Principal,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'customer' : IDL.Principal,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const CreateOrderArgs = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'restaurantId' : RestaurantId,
  'phone' : IDL.Text,
  'items' : IDL.Vec(
    IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : MenuItemId })
  ),
});
export const CreateReviewArgs = IDL.Record({
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UpdateMenuItemArgs = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMenuItem' : IDL.Func([CreateMenuItemArgs], [MenuItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getRestaurant' : IDL.Func([RestaurantId], [IDL.Opt(Restaurant)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
  'listOrdersByCustomer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listOrdersByRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'listReviewsByRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([CreateOrderArgs], [Order], []),
  'registerCustomer' : IDL.Func([IDL.Text, IDL.Text], [CustomerProfile], []),
  'registerRestaurant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Restaurant],
      [],
    ),
  'submitReview' : IDL.Func([CreateReviewArgs], [Review], []),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, UpdateMenuItemArgs],
      [IDL.Opt(MenuItem)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RestaurantId = IDL.Text;
  const CreateMenuItemArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Restaurant = IDL.Record({
    'rid' : RestaurantId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Ready' : IDL.Null,
    'Preparing' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customer' : IDL.Principal,
    'createdAt' : Timestamp,
    'restaurantId' : RestaurantId,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'customer' : IDL.Principal,
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const CreateOrderArgs = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'restaurantId' : RestaurantId,
    'phone' : IDL.Text,
    'items' : IDL.Vec(
      IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : MenuItemId })
    ),
  });
  const CreateReviewArgs = IDL.Record({
    'orderId' : OrderId,
    'restaurantId' : RestaurantId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UpdateMenuItemArgs = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMenuItem' : IDL.Func([CreateMenuItemArgs], [MenuItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'getMyRestaurant' : IDL.Func([], [IDL.Opt(Restaurant)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(Restaurant)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMenuItems' : IDL.Func([RestaurantId], [IDL.Vec(MenuItem)], ['query']),
    'listOrdersByCustomer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listOrdersByRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'listReviewsByRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([CreateOrderArgs], [Order], []),
    'registerCustomer' : IDL.Func([IDL.Text, IDL.Text], [CustomerProfile], []),
    'registerRestaurant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Restaurant],
        [],
      ),
    'submitReview' : IDL.Func([CreateReviewArgs], [Review], []),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, UpdateMenuItemArgs],
        [IDL.Opt(MenuItem)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };