/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateMenuItemArgs {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [string],
  'category' : string,
  'price' : bigint,
}
export interface CreateOrderArgs {
  'customerName' : string,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'restaurantId' : RestaurantId,
  'phone' : string,
  'items' : Array<{ 'quantity' : bigint, 'menuItemId' : MenuItemId }>,
}
export interface CreateReviewArgs {
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'rating' : bigint,
}
export interface CustomerProfile {
  'principal' : Principal,
  'name' : string,
  'phone' : string,
}
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [string],
  'category' : string,
  'price' : bigint,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'customer' : Principal,
  'createdAt' : Timestamp,
  'restaurantId' : RestaurantId,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'Ready' : null } |
  { 'Preparing' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null };
export interface Restaurant {
  'rid' : RestaurantId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type RestaurantId = string;
export interface Review {
  'id' : ReviewId,
  'customer' : Principal,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'restaurantId' : RestaurantId,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export type Timestamp = bigint;
export interface UpdateMenuItemArgs {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : [] | [string],
  'category' : string,
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMenuItem' : ActorMethod<[CreateMenuItemArgs], MenuItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMenuItem' : ActorMethod<[MenuItemId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getMyRestaurant' : ActorMethod<[], [] | [Restaurant]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [Restaurant]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMenuItems' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'listOrdersByCustomer' : ActorMethod<[], Array<Order>>,
  'listOrdersByRestaurant' : ActorMethod<[RestaurantId], Array<Order>>,
  'listRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'listReviewsByRestaurant' : ActorMethod<[RestaurantId], Array<Review>>,
  'placeOrder' : ActorMethod<[CreateOrderArgs], Order>,
  'registerCustomer' : ActorMethod<[string, string], CustomerProfile>,
  'registerRestaurant' : ActorMethod<
    [string, string, string, string],
    Restaurant
  >,
  'submitReview' : ActorMethod<[CreateReviewArgs], Review>,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, UpdateMenuItemArgs],
    [] | [MenuItem]
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];