/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateOrderArgs {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    restaurantId: RestaurantId;
    phone: string;
    items: Array<{
        quantity: bigint;
        menuItemId: MenuItemId;
    }>;
}
export interface CreateMenuItemArgs {
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: string;
    price: bigint;
}
export type Timestamp = bigint;
export interface OrderItem {
    name: string;
    quantity: bigint;
    price: bigint;
    menuItemId: MenuItemId;
}
export interface CustomerProfile {
    principal: Principal;
    name: string;
    phone: string;
}
export type RestaurantId = string;
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customer: Principal;
    createdAt: Timestamp;
    restaurantId: RestaurantId;
    phone: string;
    items: Array<OrderItem>;
}
export interface Restaurant {
    rid: RestaurantId;
    owner: Principal;
    name: string;
    createdAt: Timestamp;
    email: string;
    address: string;
    phone: string;
}
export interface MenuItem {
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: string;
    price: bigint;
}
export interface UpdateMenuItemArgs {
    name: string;
    description: string;
    available: boolean;
    imageUrl?: string;
    category: string;
    price: bigint;
}
export type MenuItemId = bigint;
export type ReviewId = bigint;
export interface CreateReviewArgs {
    orderId: OrderId;
    restaurantId: RestaurantId;
    comment: string;
    rating: bigint;
}
export interface Review {
    id: ReviewId;
    customer: Principal;
    createdAt: Timestamp;
    orderId: OrderId;
    restaurantId: RestaurantId;
    comment: string;
    rating: bigint;
}
export type OrderId = bigint;
export enum OrderStatus {
    Ready = "Ready",
    Preparing = "Preparing",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum PaymentMethod {
    UPI = "UPI",
    Card = "Card",
    Cash = "Cash"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addMenuItem(args: CreateMenuItemArgs): Promise<MenuItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteMenuItem(id: MenuItemId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerProfile(): Promise<CustomerProfile | null>;
    getMyRestaurant(): Promise<Restaurant | null>;
    getOrder(id: OrderId): Promise<Order | null>;
    getRestaurant(rid: RestaurantId): Promise<Restaurant | null>;
    isCallerAdmin(): Promise<boolean>;
    listMenuItems(restaurantId: RestaurantId): Promise<Array<MenuItem>>;
    listOrdersByCustomer(): Promise<Array<Order>>;
    listOrdersByRestaurant(restaurantId: RestaurantId): Promise<Array<Order>>;
    listRestaurants(): Promise<Array<Restaurant>>;
    listReviewsByRestaurant(restaurantId: RestaurantId): Promise<Array<Review>>;
    placeOrder(args: CreateOrderArgs): Promise<Order>;
    registerCustomer(name: string, phone: string): Promise<CustomerProfile>;
    registerRestaurant(name: string, phone: string, address: string, email: string): Promise<Restaurant>;
    submitReview(args: CreateReviewArgs): Promise<Review>;
    updateMenuItem(id: MenuItemId, args: UpdateMenuItemArgs): Promise<MenuItem | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
}
import type { CreateMenuItemArgs as _CreateMenuItemArgs, CreateOrderArgs as _CreateOrderArgs, CustomerProfile as _CustomerProfile, MenuItem as _MenuItem, MenuItemId as _MenuItemId, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Restaurant as _Restaurant, RestaurantId as _RestaurantId, Timestamp as _Timestamp, UpdateMenuItemArgs as _UpdateMenuItemArgs, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addMenuItem(arg0: CreateMenuItemArgs): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_CreateMenuItemArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MenuItem_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_CreateMenuItemArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MenuItem_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMenuItem(arg0: MenuItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRestaurant(): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRestaurant();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRestaurant();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMenuItems(arg0: RestaurantId): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMenuItems(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMenuItems(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrdersByCustomer(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrdersByCustomer();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrdersByCustomer();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrdersByRestaurant(arg0: RestaurantId): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrdersByRestaurant(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrdersByRestaurant(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurants();
            return result;
        }
    }
    async listReviewsByRestaurant(arg0: RestaurantId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReviewsByRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReviewsByRestaurant(arg0);
            return result;
        }
    }
    async placeOrder(arg0: CreateOrderArgs): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_CreateOrderArgs_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_CreateOrderArgs_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(arg0: string, arg1: string): Promise<CustomerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1);
            return result;
        }
    }
    async registerRestaurant(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRestaurant(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRestaurant(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitReview(arg0: CreateReviewArgs): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: UpdateMenuItemArgs): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_UpdateMenuItemArgs_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_UpdateMenuItemArgs_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MenuItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Restaurant | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    paymentMethod: _PaymentMethod;
    customer: Principal;
    createdAt: _Timestamp;
    restaurantId: _RestaurantId;
    phone: string;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customer: Principal;
    createdAt: Timestamp;
    restaurantId: RestaurantId;
    phone: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n15(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        paymentMethod: from_candid_PaymentMethod_n17(_uploadFile, _downloadFile, value.paymentMethod),
        customer: value.customer,
        createdAt: value.createdAt,
        restaurantId: value.restaurantId,
        phone: value.phone,
        items: value.items
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: _RestaurantId;
    imageUrl: [] | [string];
    category: string;
    price: bigint;
}): {
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        restaurantId: value.restaurantId,
        imageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.imageUrl)),
        category: value.category,
        price: value.price
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ready: null;
} | {
    Preparing: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Ready" in value ? OrderStatus.Ready : "Preparing" in value ? OrderStatus.Preparing : "Cancelled" in value ? OrderStatus.Cancelled : "Completed" in value ? OrderStatus.Completed : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Card" in value ? PaymentMethod.Card : "Cash" in value ? PaymentMethod.Cash : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n13(_uploadFile, _downloadFile, x));
}
function to_candid_CreateMenuItemArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMenuItemArgs): _CreateMenuItemArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderArgs_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderArgs): _CreateOrderArgs {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMenuItemArgs_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMenuItemArgs): _UpdateMenuItemArgs {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: string;
    category: string;
    price: bigint;
}): {
    name: string;
    description: string;
    available: boolean;
    restaurantId: _RestaurantId;
    imageUrl: [] | [string];
    category: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        restaurantId: value.restaurantId,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: value.category,
        price: value.price
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    restaurantId: RestaurantId;
    phone: string;
    items: Array<{
        quantity: bigint;
        menuItemId: MenuItemId;
    }>;
}): {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: _PaymentMethod;
    restaurantId: _RestaurantId;
    phone: string;
    items: Array<{
        quantity: bigint;
        menuItemId: _MenuItemId;
    }>;
} {
    return {
        customerName: value.customerName,
        deliveryAddress: value.deliveryAddress,
        paymentMethod: to_candid_PaymentMethod_n23(_uploadFile, _downloadFile, value.paymentMethod),
        restaurantId: value.restaurantId,
        phone: value.phone,
        items: value.items
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    imageUrl?: string;
    category: string;
    price: bigint;
}): {
    name: string;
    description: string;
    available: boolean;
    imageUrl: [] | [string];
    category: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: value.category,
        price: value.price
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Card: null;
} | {
    Cash: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Card ? {
        Card: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Ready: null;
} | {
    Preparing: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Preparing ? {
        Preparing: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Completed ? {
        Completed: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
